--удаляю все ранее созданные таблицы поскольку для postman нужно что бы нумерация создаваемых в тестах записей начиналась с единицы
DROP TABLE IF EXISTS FILM_GENRE, FRIEND, LIKES;
DROP TABLE IF EXISTS FILM;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS FRIENDSHIP_STATUS;

--создаю все таблицы нужные для решения
CREATE TABLE IF NOT EXISTS film
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description varchar(10000),
    releaseDate date,
    duration    integer,
    rating_id   integer
);

CREATE TABLE IF NOT EXISTS genre
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int,
    genre_id int,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS rating
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10)
);


CREATE TABLE IF NOT EXISTS users
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  varchar(255),
    login  varchar(20),
    name   varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id int,
    user_id int,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friend
(
    user_id_from int,
    user_id_to   int,
    status_id    int,
    PRIMARY KEY (user_id_from, user_id_to)
);

CREATE TABLE IF NOT EXISTS friendship_status
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

ALTER TABLE film_genre
    ADD FOREIGN KEY (film_id) REFERENCES film (id);

ALTER TABLE film_genre
    ADD FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE film
    ADD FOREIGN KEY (rating_id) REFERENCES rating (id);

ALTER TABLE likes
    ADD FOREIGN KEY (film_id) REFERENCES film (id);

ALTER TABLE likes
    ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE friend
    ADD FOREIGN KEY (status_id) REFERENCES friendship_status (id);

ALTER TABLE friend
    ADD FOREIGN KEY (user_id_from) REFERENCES users (id);

ALTER TABLE friend
    ADD FOREIGN KEY (user_id_to) REFERENCES users (id);

